version: "3.8"

services:
  web:
    build: .
    image: usaspend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_PATH=/data/app.db
    volumes:
      - ./data:/data
      - ./exports:/app/exports
      - ./templates:/app/templates:ro
    restart: unless-stopped

  worker:
    image: usaspend:latest
    depends_on:
      - web
    env_file:
      - .env
    environment:
      - DB_PATH=/data/app.db
    command: ["python", "-m", "src.cli", "schedule", "--cron", "0 2 * * *"]
    volumes:
      - ./data:/data
      - ./exports:/app/exports
    restart: unless-stopped

volumes:
  data:
  exports:

